### ISSUE TITLE
Can't upgrade from Nuget

### ISSUE THREAD

**Issue by timgaunt** [CaptiveAire/Seq.App.YouTrack#12]
There's an update available but when trying to upgrade @Jaben I get the error 

Package Seq.App.YouTrack could not be interrogated for app configuration: no type marked with `[SeqApp]` could be found.

**Comment by Jaben** [comment]
This version is Seq v5.1+ only. You will need a new version of Seq.

**Comment by Jaben** [comment]
@nblumhardt is there any way to set a lower bound for the Seq plug-in?

**Comment by timgaunt** [comment]
Ah sorry I read it as 5+, we'll upgrade now

**Comment by Jaben** [comment]
I don't get time to upgrade it much -- so figured I just put everything on latest. Slightly painful in the short term, though.

**Comment by timgaunt** [comment]
Makes sense, latest version works for me, we're updated and resolved ta

**Comment by nblumhardt** [comment]
The new version of _Seq.Apps_ does contain a few features that aren't usable in earlier versions, but if you want to keep the code running in earlier hosts it _should_ be possible to derive `YouTrackIssuePoster` from `Reactor` instead of `SeqApp`.

The challenge is that Seq will always load up its native version of `Seq.Apps.dll` to interface with the app. If a plug-in type like `YouTrackIssuePoster` only touches types from `Seq.Apps.dll` that are present in the native version of that assembly for the target Seq version, everything should load up okay.

To move the APIs forward gracefully, the new `SeqApp` type was slipped in between `Reactor` (obsolete) and `System.Object`. Apps that derive from `SeqApp` will need this to load, and so they'll only load up in the newer Seq version.

Apps that derive from `Reactor` should load up in both versions. The inheritance hierarchy will change, but as long as the `Reactor`-derived type only touches surface area present on `Reactor` in both versions (doesn't inadvertently depend on methods/ctors/props declared on `SeqApp`), the loader should be happy.

Whether or not it's worth the hassle, and worth sticking with the old API, is another question. I personally assume that people who frequently update apps will probably also be updating Seq on a similar schedule. May not always be the case, though :-)

**Comment by Jaben** [comment]
Thanks @nblumhardt -- yeah, I probably should have targeted Reactor -- at least in the short term.
